// frontend-lm/src/pages/leads/LeadDetail.tsx
import React, { useState, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { leadsService } from 'services/leads';
import { Card } from 'components/ui/Card';
import { Button } from 'components/ui/Button';
import { Badge } from 'components/ui/Badge';
import { PageHeader } from 'components/layout/PageHeader';
import { LoadingSpinner } from 'components/ui/LoadingSpinner';
import { Alert } from 'components/ui/Alert';
import { routes } from 'routes';
import { LEAD_STATUS_CONFIG } from 'types';
import type { Lead } from 'types';
import { 
  PencilIcon, 
  TrashIcon, 
  ArrowLeftIcon,
  EnvelopeIcon,
  BuildingOfficeIcon,
  CalendarIcon,
  ClockIcon
} from '@heroicons/react/24/outline';

export const LeadDetail: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [lead, setLead] = useState<Lead | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [updatingStatus, setUpdatingStatus] = useState(false);

  useEffect(() => {
    if (id) {
      loadLead(parseInt(id));
    }
  }, [id]);

  const loadLead = async (leadId: number) => {
    try {
      setLoading(true);
      const data = await leadsService.getLead(leadId);
      setLead(data);
      setError(null);
    } catch (err: any) {
      setError('Error al cargar el lead');
      console.error('Error loading lead:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleStatusChange = async (newStatus: string) => {
    if (!lead) return;
    
    try {
      setUpdatingStatus(true);
      await leadsService.updateLeadStatus(lead.id, newStatus);
      await loadLead(lead.id);
    } catch (err: any) {
      setError('Error al actualizar el estado del lead');
    } finally {
      setUpdatingStatus(false);
    }
  };

  const handleDeleteLead = async () => {
    if (!lead) return;
    
    if (window.confirm('¿Estás seguro de que quieres eliminar este lead? Esta acción no se puede deshacer.')) {
      try {
        await leadsService.deleteLead(lead.id);
        navigate(routes.app.leads);
      } catch (err: any) {
        setError('Error al eliminar el lead');
      }
    }
  };

  const getStatusConfig = (status: string) => {
    return LEAD_STATUS_CONFIG[status as keyof typeof LEAD_STATUS_CONFIG] || {
      label: status,
      color: 'text-gray-500',
      bgColor: 'bg-gray-100',
      icon: '📋'
    };
  };

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    });
  };

  if (loading) {
    return (
      <div className="flex justify-center items-center h-64">
        <LoadingSpinner />
      </div>
    );
  }

  if (!lead) {
    return (
      <div className="text-center py-12">
        <Alert type="error">Lead no encontrado</Alert>
      </div>
    );
  }

  const statusConfig = getStatusConfig(lead.status);

  return (
    <div className="space-y-6">
      <PageHeader
        title={`${lead.first_name} ${lead.last_name}`}
        subtitle="Detalles del lead"
        breadcrumbs={[
          { name: 'Inicio', href: routes.app.dashboard },
          { name: 'Leads', href: routes.app.leads },
          { name: `${lead.first_name} ${lead.last_name}` },
        ]}
        actions={
          <div className="flex gap-2">
            <Button
              variant="outline"
              onClick={() => navigate(routes.app.leads)}
              icon={<ArrowLeftIcon className="w-4 h-4" />}
            >
              Volver
            </Button>
            <Button
              variant="outline"
              onClick={() => navigate(`${routes.app.leadForm}?id=${lead.id}`)}
              icon={<PencilIcon className="w-4 h-4" />}
            >
              Editar
            </Button>
            <Button
              variant="danger"
              onClick={handleDeleteLead}
              icon={<TrashIcon className="w-4 h-4" />}
            >
              Eliminar
            </Button>
          </div>
        }
      />

      {error && (
        <Alert type="error">{error}</Alert>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Información Principal */}
        <div className="lg:col-span-2 space-y-6">
          <Card>
            <div className="p-6">
              <div className="flex items-start justify-between mb-6">
                <div className="flex items-center gap-4">
                  <div className="w-16 h-16 bg-primary-start bg-opacity-10 rounded-full flex items-center justify-center">
                    <span className="text-primary-start text-2xl font-bold">
                      {lead.first_name[0]}{lead.last_name[0]}
                    </span>
                  </div>
                  <div>
                    <h2 className="text-2xl font-bold text-light-100">
                      {lead.first_name} {lead.last_name}
                    </h2>
                    <p className="text-light-300">{lead.company || 'Sin empresa'}</p>
                  </div>
                </div>
                <Badge 
                  variant="primary" 
                  className={`${statusConfig.bgColor} ${statusConfig.color} text-lg px-4 py-2`}
                >
                  <span className="mr-2">{statusConfig.icon}</span>
                  {statusConfig.label}
                </Badge>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div className="space-y-4">
                  <div className="flex items-center gap-3">
                    <EnvelopeIcon className="w-5 h-5 text-light-300" />
                    <div>
                      <p className="text-sm text-light-300">Email</p>
                      <p className="text-light-100 font-medium">{lead.email}</p>
                    </div>
                  </div>
                  
                  {lead.company && (
                    <div className="flex items-center gap-3">
                      <BuildingOfficeIcon className="w-5 h-5 text-light-300" />
                      <div>
                        <p className="text-sm text-light-300">Empresa</p>
                        <p className="text-light-100 font-medium">{lead.company}</p>
                      </div>
                    </div>
                  )}
                </div>

                <div className="space-y-4">
                  <div className="flex items-center gap-3">
                    <CalendarIcon className="w-5 h-5 text-light-300" />
                    <div>
                      <p className="text-sm text-light-300">Fecha de Creación</p>
                      <p className="text-light-100 font-medium">{formatDate(lead.date_created)}</p>
                    </div>
                  </div>
                  
                  <div className="flex items-center gap-3">
                    <ClockIcon className="w-5 h-5 text-light-300" />
                    <div>
                      <p className="text-sm text-light-300">Última Actualización</p>
                      <p className="text-light-100 font-medium">{formatDate(lead.date_last_updated)}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </Card>

          {/* Notas */}
          {lead.note && (
            <Card>
              <div className="p-6">
                <h3 className="text-lg font-semibold text-light-100 mb-4">Notas</h3>
                <div className="bg-dark-800 p-4 rounded-lg">
                  <p className="text-light-200 whitespace-pre-wrap">{lead.note}</p>
                </div>
              </div>
            </Card>
          )}
        </div>

        {/* Panel Lateral */}
        <div className="space-y-6">
          {/* Estado del Lead */}
          <Card>
            <div className="p-6">
              <h3 className="text-lg font-semibold text-light-100 mb-4">Estado del Lead</h3>
              <div className="space-y-3">
                <div>
                  <label className="form-label">Cambiar Estado</label>
                  <select
                    className="input-field"
                    value={lead.status}
                    onChange={(e) => handleStatusChange(e.target.value)}
                    disabled={updatingStatus}
                  >
                    {Object.entries(LEAD_STATUS_CONFIG).map(([key, config]) => (
                      <option key={key} value={key}>{config.label}</option>
                    ))}
                  </select>
                </div>
                {updatingStatus && (
                  <div className="flex items-center gap-2 text-sm text-light-300">
                    <LoadingSpinner />
                    Actualizando estado...
                  </div>
                )}
              </div>
            </div>
          </Card>

          {/* Acciones Rápidas */}
          <Card>
            <div className="p-6">
              <h3 className="text-lg font-semibold text-light-100 mb-4">Acciones</h3>
              <div className="space-y-3">
                <Button
                  variant="primary"
                  className="w-full"
                  onClick={() => navigate(`${routes.app.leadForm}?id=${lead.id}`)}
                  icon={<PencilIcon className="w-4 h-4" />}
                >
                  Editar Lead
                </Button>
                <Button
                  variant="outline"
                  className="w-full"
                  onClick={() => window.open(`mailto:${lead.email}`, '_blank')}
                  icon={<EnvelopeIcon className="w-4 h-4" />}
                >
                  Enviar Email
                </Button>
                <Button
                  variant="danger"
                  className="w-full"
                  onClick={handleDeleteLead}
                  icon={<TrashIcon className="w-4 h-4" />}
                >
                  Eliminar Lead
                </Button>
              </div>
            </div>
          </Card>

          {/* Información del Sistema */}
          <Card>
            <div className="p-6">
              <h3 className="text-lg font-semibold text-light-100 mb-4">Información del Sistema</h3>
              <div className="space-y-3 text-sm">
                <div className="flex justify-between">
                  <span className="text-light-300">ID del Lead:</span>
                  <span className="text-light-100 font-mono">#{lead.id}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-light-300">Propietario:</span>
                  <span className="text-light-100">Tú</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-light-300">Creado:</span>
                  <span className="text-light-100">{new Date(lead.date_created).toLocaleDateString()}</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-light-300">Actualizado:</span>
                  <span className="text-light-100">{new Date(lead.date_last_updated).toLocaleDateString()}</span>
                </div>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
};

export default LeadDetail;

// frontend-lm/src/routes/LeadDetail.svelte
<script lang="ts">
  import { push } from 'svelte-spa-router'
  import { leadsService } from 'lib/leads'
  import { LEAD_STATUS_CONFIG, statusConfig } from 'lib/types'
  import type { Lead } from 'lib/types'
  import { routes } from 'lib/routes'
  import Card from 'lib/ui/Card.svelte'
  import Button from 'lib/ui/Button.svelte'
  import Badge from 'lib/ui/Badge.svelte'
  import LoadingSpinner from 'lib/ui/LoadingSpinner.svelte'
  import Alert from 'lib/ui/Alert.svelte'
  import PageHeader from 'layout/PageHeader.svelte'
  import PencilIcon from 'lib/icons/PencilIcon.svelte'
  import TrashIcon from 'lib/icons/TrashIcon.svelte'
  import ArrowLeftIcon from 'lib/icons/ArrowLeftIcon.svelte'
  import EnvelopeIcon from 'lib/icons/EnvelopeIcon.svelte'
  import BuildingOfficeIcon from 'lib/icons/BuildingOfficeIcon.svelte'
  import CalendarIcon from 'lib/icons/CalendarIcon.svelte'
  import ClockIcon from 'lib/icons/ClockIcon.svelte'

  // svelte-spa-router pasa los parámetros de la ruta (ej. /leads/:id) como
  // esta prop, en vez de tener que leerlos del singleton global del router.
  interface Props {
    params?: { id?: string }
  }
  let { params = {} }: Props = $props()

  let lead = $state<Lead | null>(null)
  let loading = $state(true)
  let error = $state<string | null>(null)
  let updatingStatus = $state(false)

  async function loadLead(leadId: number) {
    try {
      loading = true
      lead = await leadsService.getLead(leadId)
      error = null
    } catch {
      error = 'Error al cargar el lead'
    } finally {
      loading = false
    }
  }

  $effect(() => {
    if (params.id) loadLead(Number(params.id))
  })

  async function handleStatusChange(newStatus: string) {
    if (!lead) return
    try {
      updatingStatus = true
      await leadsService.updateLeadStatus(lead.id, newStatus)
      await loadLead(lead.id)
    } catch {
      error = 'Error al actualizar el estado del lead'
    } finally {
      updatingStatus = false
    }
  }

  async function handleDeleteLead() {
    if (!lead) return
    if (!window.confirm('¿Estás seguro de que quieres eliminar este lead? Esta acción no se puede deshacer.')) return
    try {
      await leadsService.deleteLead(lead.id)
      push(routes.app.leads)
    } catch {
      error = 'Error al eliminar el lead'
    }
  }

  function formatDate(dateString: string) {
    return new Date(dateString).toLocaleDateString('es-ES', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })
  }
</script>

{#if loading}
  <div class="flex justify-center items-center h-64">
    <LoadingSpinner />
  </div>
{:else if !lead}
  <div class="text-center py-12">
    <Alert type="error">Lead no encontrado</Alert>
  </div>
{:else}
  {@const config = statusConfig(lead.status)}
  <div class="space-y-6">
    <PageHeader
      title="{lead.first_name} {lead.last_name}"
      subtitle="Detalles del lead"
      breadcrumbs={[
        { name: 'Inicio', href: routes.app.dashboard },
        { name: 'Leads', href: routes.app.leads },
        { name: `${lead.first_name} ${lead.last_name}` },
      ]}
    >
      {#snippet actions()}
        <div class="flex gap-2">
          <Button variant="outline" onclick={() => push(routes.app.leads)}>
            {#snippet icon()}<ArrowLeftIcon class="w-4 h-4" />{/snippet}
            Volver
          </Button>
          <Button variant="outline" onclick={() => push(`${routes.app.leadForm}?id=${lead!.id}`)}>
            {#snippet icon()}<PencilIcon class="w-4 h-4" />{/snippet}
            Editar
          </Button>
          <Button variant="danger" onclick={handleDeleteLead}>
            {#snippet icon()}<TrashIcon class="w-4 h-4" />{/snippet}
            Eliminar
          </Button>
        </div>
      {/snippet}
    </PageHeader>

    {#if error}<Alert type="error">{error}</Alert>{/if}

    <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
      <div class="lg:col-span-2 space-y-6">
        <Card>
          <div class="flex items-start justify-between mb-6">
            <div class="flex items-center gap-4">
              <div class="w-14 h-14 rounded-full bg-accent/12 flex items-center justify-center shrink-0">
                <span class="text-accent text-xl font-semibold">{lead.first_name[0]}{lead.last_name[0]}</span>
              </div>
              <div>
                <h2 class="text-xl font-semibold text-text">{lead.first_name} {lead.last_name}</h2>
                <p class="text-text-secondary text-sm">{lead.company || 'Sin empresa'}</p>
              </div>
            </div>
            <Badge class="{config.badgeClass} text-sm">{config.label}</Badge>
          </div>

          <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div class="space-y-4">
              <div class="flex items-center gap-3">
                <EnvelopeIcon class="w-5 h-5 text-text-muted" />
                <div>
                  <p class="text-xs text-text-muted">Email</p>
                  <p class="text-text text-sm font-medium">{lead.email}</p>
                </div>
              </div>
              {#if lead.company}
                <div class="flex items-center gap-3">
                  <BuildingOfficeIcon class="w-5 h-5 text-text-muted" />
                  <div>
                    <p class="text-xs text-text-muted">Empresa</p>
                    <p class="text-text text-sm font-medium">{lead.company}</p>
                  </div>
                </div>
              {/if}
            </div>

            <div class="space-y-4">
              <div class="flex items-center gap-3">
                <CalendarIcon class="w-5 h-5 text-text-muted" />
                <div>
                  <p class="text-xs text-text-muted">Fecha de creación</p>
                  <p class="text-text text-sm font-medium">{formatDate(lead.date_created)}</p>
                </div>
              </div>
              <div class="flex items-center gap-3">
                <ClockIcon class="w-5 h-5 text-text-muted" />
                <div>
                  <p class="text-xs text-text-muted">Última actualización</p>
                  <p class="text-text text-sm font-medium">{formatDate(lead.date_last_updated)}</p>
                </div>
              </div>
            </div>
          </div>
        </Card>

        {#if lead.note}
          <Card title="Notas">
            <div class="bg-page p-4 rounded-xl">
              <p class="text-text text-sm whitespace-pre-wrap">{lead.note}</p>
            </div>
          </Card>
        {/if}
      </div>

      <div class="space-y-6">
        <Card title="Estado del lead">
          <div class="space-y-3">
            <div>
              <span class="form-label">Cambiar estado</span>
              <select
                class="input-field"
                value={lead.status}
                disabled={updatingStatus}
                onchange={(e) => handleStatusChange(e.currentTarget.value)}
              >
                {#each Object.entries(LEAD_STATUS_CONFIG) as [key, opt] (key)}
                  <option value={key}>{opt.label}</option>
                {/each}
              </select>
            </div>
            {#if updatingStatus}
              <div class="flex items-center gap-2 text-sm text-text-muted">
                <LoadingSpinner size="sm" />
                Actualizando estado...
              </div>
            {/if}
          </div>
        </Card>

        <Card title="Acciones">
          <div class="space-y-2">
            <Button variant="primary" class="w-full" onclick={() => push(`${routes.app.leadForm}?id=${lead!.id}`)}>
              {#snippet icon()}<PencilIcon class="w-4 h-4" />{/snippet}
              Editar lead
            </Button>
            <Button variant="outline" class="w-full" onclick={() => window.open(`mailto:${lead!.email}`, '_blank')}>
              {#snippet icon()}<EnvelopeIcon class="w-4 h-4" />{/snippet}
              Enviar email
            </Button>
            <Button variant="danger" class="w-full" onclick={handleDeleteLead}>
              {#snippet icon()}<TrashIcon class="w-4 h-4" />{/snippet}
              Eliminar lead
            </Button>
          </div>
        </Card>

        <Card title="Información del sistema">
          <div class="space-y-2.5 text-sm">
            <div class="flex justify-between">
              <span class="text-text-muted">ID del lead</span>
              <span class="text-text font-mono">#{lead.id}</span>
            </div>
            <div class="flex justify-between">
              <span class="text-text-muted">Creado</span>
              <span class="text-text">{new Date(lead.date_created).toLocaleDateString()}</span>
            </div>
            <div class="flex justify-between">
              <span class="text-text-muted">Actualizado</span>
              <span class="text-text">{new Date(lead.date_last_updated).toLocaleDateString()}</span>
            </div>
          </div>
        </Card>
      </div>
    </div>
  </div>
{/if}
