// frontend-lm/src/layout/Header.svelte
<script lang="ts">
  import Bars3Icon from 'lib/icons/Bars3Icon.svelte'
  import XMarkIcon from 'lib/icons/XMarkIcon.svelte'
  import UserIcon from 'lib/icons/UserIcon.svelte'
  import ArrowRightOnRectangleIcon from 'lib/icons/ArrowRightOnRectangleIcon.svelte'
  import { mobileMenuOpen } from 'lib/stores/layout'
  import { user, logout } from 'lib/stores/auth'
  import { navigationItems } from 'lib/navigation'
  import { link, router } from 'svelte-spa-router'

  let userMenuOpen = $state(false)

  const displayName = $derived($user?.email.split('@')[0] ?? '')

  function handleLogout() {
    userMenuOpen = false
    mobileMenuOpen.set(false)
    logout()
  }
</script>

<header class="sticky top-0 z-40 bg-surface/90 backdrop-blur border-b border-border">
  <div class="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center gap-8">
        <a href="/dashboard" use:link class="flex items-center gap-2.5 shrink-0">
          <img src="/leads-manager-icon-simple.svg" alt="" class="w-7 h-7" />
          <span class="text-[15px] font-semibold text-text tracking-tight">Leads Manager</span>
        </a>

        <nav class="hidden md:flex items-center gap-1">
          {#each navigationItems as item (item.name)}
            <a
              href={item.href}
              use:link
              class="px-3 py-2 rounded-lg text-sm font-medium transition-colors {router.location === item.href
                ? 'text-accent bg-accent/8'
                : 'text-text-secondary hover:text-text hover:bg-surface-raised'}"
            >
              {item.name}
            </a>
          {/each}
        </nav>
      </div>

      <div class="flex items-center gap-2">
        <button
          onclick={() => mobileMenuOpen.update((v) => !v)}
          class="md:hidden p-2 rounded-lg text-text-secondary hover:bg-surface-raised"
          aria-label="Abrir menú"
        >
          {#if $mobileMenuOpen}<XMarkIcon class="w-5 h-5" />{:else}<Bars3Icon class="w-5 h-5" />{/if}
        </button>

        <div class="relative hidden md:block">
          <button
            onclick={() => (userMenuOpen = !userMenuOpen)}
            class="flex items-center gap-2.5 p-1.5 pr-3 rounded-full hover:bg-surface-raised transition-colors"
          >
            <div class="w-7 h-7 rounded-full bg-accent/12 flex items-center justify-center">
              <UserIcon class="w-4 h-4 text-accent" />
            </div>
            <span class="text-sm font-medium text-text">{displayName}</span>
          </button>

          {#if userMenuOpen}
            <div class="absolute right-0 mt-2 w-44 bg-surface border border-border rounded-xl shadow-lg py-1 z-50">
              <a
                href="/profile"
                use:link
                onclick={() => (userMenuOpen = false)}
                class="block px-3.5 py-2 text-sm text-text hover:bg-surface-raised"
              >
                Mi perfil
              </a>
              <hr class="border-divider my-1" />
              <button
                onclick={handleLogout}
                class="w-full text-left flex items-center gap-2 px-3.5 py-2 text-sm text-critical hover:bg-surface-raised"
              >
                <ArrowRightOnRectangleIcon class="w-4 h-4" />
                Cerrar sesión
              </button>
            </div>
          {/if}
        </div>
      </div>
    </div>

    {#if $mobileMenuOpen}
      <nav class="md:hidden pb-4 space-y-1">
        {#each navigationItems as item (item.name)}
          <a
            href={item.href}
            use:link
            onclick={() => mobileMenuOpen.set(false)}
            class="block px-3 py-2 rounded-lg text-sm font-medium {router.location === item.href
              ? 'text-accent bg-accent/8'
              : 'text-text-secondary hover:bg-surface-raised'}"
          >
            {item.name}
          </a>
        {/each}
        <hr class="border-divider my-2" />
        <button
          onclick={handleLogout}
          class="w-full text-left flex items-center gap-2 px-3 py-2 rounded-lg text-sm text-critical hover:bg-surface-raised"
        >
          <ArrowRightOnRectangleIcon class="w-4 h-4" />
          Cerrar sesión
        </button>
      </nav>
    {/if}
  </div>
</header>

// frontend-lm/src/components/layout/Header.tsx
import React, { useState } from 'react';
import { Bars3Icon, MagnifyingGlassIcon, BellIcon, UserIcon, ArrowRightOnRectangleIcon } from '@heroicons/react/24/outline';
import { useLayout } from './LayoutProvider';
import { useAuth } from 'hooks/useAuth';
import { useNavigate } from 'react-router-dom';

export const Header: React.FC = () => {
  const { sidebarOpen, setSidebarOpen } = useLayout();
  const [userMenuOpen, setUserMenuOpen] = useState(false);
  const { logout, user } = useAuth();
  const navigate = useNavigate();

  const handleLogout = () => {
    setUserMenuOpen(false); // Cerrar el menú
    logout();
  };

  // Extraer nombre y apellido del usuario
  let fullName = 'Usuario';
  let userType = 'user';
  if (user) {
    if (user.full_name) {
      fullName = user.full_name;
    } else if (user.first_name && user.last_name) {
      fullName = `${user.first_name} ${user.last_name}`;
    } else if (user.email) {
      fullName = user.email.split('@')[0];
    }
    // Si en el futuro hay roles, aquí se puede ajustar
    userType = 'user';
  }

  return (
    <header className="bg-dark-800 border-b border-dark-700 sticky top-0 z-40">
      <div className="flex items-center justify-between px-4 py-3 sm:px-6 lg:px-8">
        {/* Left side */}
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-2">
            <img src="/leads-manager-icon-simple.svg" alt="Logo Leads Manager" className="w-8 h-8 md:w-10 md:h-10 filter invert" />
            <span className="text-xl md:text-2xl font-bold text-white">Leads Manager</span>
          </div>
          <button
            onClick={() => setSidebarOpen(!sidebarOpen)}
            className="lg:hidden p-2 rounded-md text-light-300 hover:text-light-100 hover:bg-dark-700 transition-colors"
          >
            <Bars3Icon className="w-6 h-6" />
          </button>
          <div className="hidden sm:block">
            <div className="relative">
              <MagnifyingGlassIcon className="absolute left-3 top-1/2 transform -translate-y-1/2 w-5 h-5 text-light-300" />
              <input
                type="text"
                placeholder="Buscar leads..."
                className="w-64 pl-10 pr-4 py-2 bg-dark-700 border border-dark-600 rounded-lg text-light-100 placeholder-light-300 focus:outline-none focus:ring-2 focus:ring-primary-start focus:border-transparent"
              />
            </div>
          </div>
        </div>
        {/* Right side */}
        <div className="flex items-center gap-4">
          {/* Notifications */}
          <button className="relative p-2 text-light-300 hover:text-light-100 hover:bg-dark-700 rounded-lg transition-colors">
            <BellIcon className="w-6 h-6" />
            <span className="absolute -top-1 -right-1 w-3 h-3 bg-red-500 rounded-full"></span>
          </button>
          {/* User menu */}
          <div className="relative">
            <button
              onClick={() => setUserMenuOpen(!userMenuOpen)}
              className="flex items-center gap-3 p-2 rounded-lg hover:bg-dark-700 transition-colors"
            >
              <div className="w-8 h-8 bg-gradient-primary rounded-full flex items-center justify-center">
                <UserIcon className="w-5 h-5 text-white" />
              </div>
              <div className="hidden md:block text-left">
                <p className="text-sm font-medium text-light-100">
                  {fullName}
                </p>
                <p className="text-xs text-primary-end font-semibold uppercase tracking-wider">
                  {userType}
                </p>
              </div>
            </button>
            {/* Dropdown menu */}
            {userMenuOpen && (
              <div className="absolute right-0 mt-2 w-48 bg-dark-800 border border-dark-700 rounded-lg shadow-lg py-1 z-50">
                <button
                  onClick={() => { setUserMenuOpen(false); navigate('/profile'); }}
                  className="block w-full text-left px-4 py-2 text-sm text-light-200 hover:bg-dark-700 hover:text-light-100"
                >
                  Mi Perfil
                </button>
                <a href="#" className="block px-4 py-2 text-sm text-light-200 hover:bg-dark-700 hover:text-light-100">
                  Configuración
                </a>
                <hr className="border-dark-700 my-1" />
                <button
                  onClick={handleLogout}
                  className="w-full text-left flex items-center gap-2 px-4 py-2 text-sm text-light-200 hover:bg-dark-700 hover:text-light-100 transition-colors"
                >
                  <ArrowRightOnRectangleIcon className="w-5 h-5" />
                  <span>Cerrar sesión</span>
                </button>
              </div>
            )}
          </div>
        </div>
      </div>
    </header>
  );
};
