// frontend-lm/src/layout/PageHeader.svelte
<script lang="ts">
  import { link } from 'svelte-spa-router'
  import type { Snippet } from 'svelte'

  interface Crumb {
    name: string
    href?: string
  }

  interface Props {
    title: string
    subtitle?: string
    breadcrumbs?: Crumb[]
    actions?: Snippet
  }

  let { title, subtitle, breadcrumbs, actions }: Props = $props()
</script>

<div class="mb-8">
  {#if breadcrumbs}
    <nav class="mb-3">
      <ol class="flex items-center flex-wrap gap-x-2 text-sm text-text-secondary">
        {#each breadcrumbs as crumb, index (crumb.name)}
          <li class="flex items-center gap-x-2">
            {#if index > 0}<span class="text-text-muted">/</span>{/if}
            {#if crumb.href}
              <a href={crumb.href} use:link class="hover:text-text transition-colors">{crumb.name}</a>
            {:else}
              <span class="text-text">{crumb.name}</span>
            {/if}
          </li>
        {/each}
      </ol>
    </nav>
  {/if}
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
    <div>
      <h1 class="text-xl font-semibold text-text tracking-tight">{title}</h1>
      {#if subtitle}<p class="mt-1 text-sm text-text-secondary">{subtitle}</p>{/if}
    </div>
    {#if actions}
      <div class="flex items-center gap-2">
        {@render actions()}
      </div>
    {/if}
  </div>
</div>

// frontend-lm/src/components/layout/PageHeader.tsx
import React from 'react';

export const PageHeader: React.FC<{
  title: string;
  subtitle?: string;
  actions?: React.ReactNode;
  breadcrumbs?: Array<{ name: string; href?: string }>;
}> = ({ title, subtitle, actions, breadcrumbs }) => {
  return (
    <div className="mb-8">
      {breadcrumbs && (
        <nav className="mb-4">
          <ol className="flex items-center space-x-2 text-sm text-light-300">
            {breadcrumbs.map((crumb, index) => (
              <li key={index} className="flex items-center">
                {index > 0 && <span className="mx-2">/</span>}
                {crumb.href ? (
                  <a href={crumb.href} className="hover:text-light-100 transition-colors">
                    {crumb.name}
                  </a>
                ) : (
                  <span className="text-light-100">{crumb.name}</span>
                )}
              </li>
            ))}
          </ol>
        </nav>
      )}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-light-100">{title}</h1>
          {subtitle && (
            <p className="mt-1 text-light-300">{subtitle}</p>
          )}
        </div>
        {actions && (
          <div className="flex items-center gap-2">
            {actions}
          </div>
        )}
      </div>
    </div>
  );
};
