// frontend-lm/src/lib/ui/Alert.svelte
<script lang="ts">
  import InformationCircleIcon from 'lib/icons/InformationCircleIcon.svelte'
  import CheckCircleIcon from 'lib/icons/CheckCircleIcon.svelte'
  import ExclamationTriangleIcon from 'lib/icons/ExclamationTriangleIcon.svelte'
  import ExclamationCircleIcon from 'lib/icons/ExclamationCircleIcon.svelte'
  import XMarkIcon from 'lib/icons/XMarkIcon.svelte'
  import type { Snippet, Component } from 'svelte'

  interface Props {
    type?: 'info' | 'success' | 'warning' | 'error'
    title?: string
    class?: string
    onclose?: () => void
    children: Snippet
  }

  let { type = 'info', title, class: className = '', onclose, children }: Props = $props()

  const config: Record<string, { icon: Component<{ class?: string }>; classes: string }> = {
    info: { icon: InformationCircleIcon, classes: 'bg-accent/8 border-accent/20 text-accent' },
    success: { icon: CheckCircleIcon, classes: 'bg-good/8 border-good/20 text-good' },
    warning: { icon: ExclamationTriangleIcon, classes: 'bg-warning/10 border-warning/25 text-[#8a5a00]' },
    error: { icon: ExclamationCircleIcon, classes: 'bg-critical/8 border-critical/20 text-critical' },
  }

  const c = $derived(config[type])
</script>

<div class="border rounded-xl p-4 {c.classes} {className}">
  <div class="flex">
    <c.icon class="w-5 h-5 flex-shrink-0" />
    <div class="ml-3 flex-1">
      {#if title}
        <h3 class="text-sm font-medium">{title}</h3>
      {/if}
      <div class="text-sm {title ? 'mt-1' : ''} text-text">
        {@render children()}
      </div>
    </div>
    {#if onclose}
      <button onclick={onclose} class="ml-auto pl-3 hover:opacity-70">
        <XMarkIcon class="w-5 h-5" />
      </button>
    {/if}
  </div>
</div>

// frontend-lm/src/components/ui/Alert.tsx
import React from 'react';
import {
  ExclamationTriangleIcon,
  CheckCircleIcon,
  InformationCircleIcon,
  ExclamationCircleIcon,
  XMarkIcon
} from '@heroicons/react/24/outline';

export interface AlertProps {
  type?: 'info' | 'success' | 'warning' | 'error';
  title?: string;
  children: React.ReactNode;
  onClose?: () => void;
  className?: string;
}

export const Alert: React.FC<AlertProps> = ({
  type = 'info',
  title,
  children,
  onClose,
  className = ''
}) => {
  const types = {
    info: {
      bg: 'bg-blue-50 border-blue-200',
      icon: InformationCircleIcon,
      iconColor: 'text-blue-500',
      textColor: 'text-blue-800'
    },
    success: {
      bg: 'bg-green-50 border-green-200',
      icon: CheckCircleIcon,
      iconColor: 'text-green-500',
      textColor: 'text-green-800'
    },
    warning: {
      bg: 'bg-yellow-50 border-yellow-200',
      icon: ExclamationTriangleIcon,
      iconColor: 'text-yellow-500',
      textColor: 'text-yellow-800'
    },
    error: {
      bg: 'bg-red-50 border-red-200',
      icon: ExclamationCircleIcon,
      iconColor: 'text-red-500',
      textColor: 'text-red-800'
    }
  };

  const config = types[type];
  const IconComponent = config.icon;

  return (
    <div className={`border rounded-lg p-4 ${config.bg} ${className}`}>
      <div className="flex">
        <IconComponent className={`w-5 h-5 ${config.iconColor} flex-shrink-0`} />
        <div className="ml-3 flex-1">
          {title && (
            <h3 className={`text-sm font-medium ${config.textColor}`}>
              {title}
            </h3>
          )}
          <div className={`text-sm ${config.textColor} ${title ? 'mt-1' : ''}`}>
            {children}
          </div>
        </div>
        {onClose && (
          <button
            onClick={onClose}
            className={`ml-auto pl-3 ${config.textColor} hover:opacity-70`}
          >
            <XMarkIcon className="w-5 h-5" />
          </button>
        )}
      </div>
    </div>
  );
};
