// frontend-lm/src/lib/ui/Button.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'

  interface Props {
    variant?: 'primary' | 'outline' | 'ghost' | 'danger'
    size?: 'sm' | 'md' | 'lg'
    disabled?: boolean
    loading?: boolean
    type?: 'button' | 'submit' | 'reset'
    class?: string
    onclick?: () => void
    icon?: Snippet
    children?: Snippet
    'aria-label'?: string
  }

  let {
    variant = 'primary',
    size = 'md',
    disabled = false,
    loading = false,
    type = 'button',
    class: className = '',
    onclick,
    icon,
    children,
    'aria-label': ariaLabel,
  }: Props = $props()

  const base =
    'inline-flex items-center justify-center font-medium rounded-lg transition-colors duration-150 focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-offset-page'

  const variants = {
    primary: 'bg-accent hover:bg-accent-hover text-white focus-visible:ring-accent',
    outline: 'border border-border text-text hover:bg-surface-raised focus-visible:ring-accent',
    ghost: 'text-text-secondary hover:bg-surface-raised hover:text-text focus-visible:ring-accent',
    danger: 'bg-critical hover:brightness-90 text-white focus-visible:ring-critical',
  } as const

  const sizes = {
    sm: 'px-3 py-1.5 text-sm gap-1.5',
    md: 'px-4 py-2 text-sm gap-2',
    lg: 'px-5 py-2.5 text-base gap-2',
  } as const
</script>

<button
  {type}
  {onclick}
  disabled={disabled || loading}
  aria-label={ariaLabel}
  class="{base} {variants[variant]} {sizes[size]} {disabled || loading ? 'opacity-50 cursor-not-allowed' : ''} {className}"
>
  {#if loading}
    <div class="animate-spin rounded-full h-4 w-4 border-2 border-current border-t-transparent"></div>
  {:else if icon}
    <span class="w-4 h-4">{@render icon()}</span>
  {/if}
  {#if children}{@render children()}{/if}
</button>

// frontend-lm/src/components/ui/Button.tsx
import React from 'react';

export interface ButtonProps {
  variant?: 'primary' | 'secondary' | 'outline' | 'ghost' | 'gradient' | 'danger';
  size?: 'sm' | 'md' | 'lg';
  disabled?: boolean;
  loading?: boolean;
  icon?: React.ReactNode;
  children: React.ReactNode;
  onClick?: () => void;
  type?: 'button' | 'submit' | 'reset';
  className?: string;
}

export const Button: React.FC<ButtonProps> = ({ 
  variant = 'primary', 
  size = 'md', 
  disabled = false, 
  loading = false, 
  icon, 
  children, 
  onClick, 
  type = 'button', 
  className = '' 
}) => {
  const baseClasses = 'inline-flex items-center justify-center font-medium rounded-lg transition-all duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-dark-900';
  
  const variants = {
    primary: 'bg-primary-start hover:bg-primary-end text-white shadow-lg hover:shadow-xl focus:ring-primary-start',
    secondary: 'bg-dark-800 hover:bg-dark-700 text-light-100 border border-dark-700 focus:ring-dark-700',
    outline: 'border border-primary-start text-primary-start hover:bg-primary-start hover:text-white focus:ring-primary-start',
    ghost: 'text-light-200 hover:bg-dark-800 hover:text-light-100 focus:ring-dark-700',
    gradient: 'bg-gradient-primary text-white shadow-lg hover:shadow-xl hover:scale-105 focus:ring-primary-start',
    danger: 'bg-red-600 hover:bg-red-700 text-white focus:ring-red-500'
  };
  
  const sizes = {
    sm: 'px-3 py-1.5 text-sm gap-1.5',
    md: 'px-4 py-2 text-sm gap-2',
    lg: 'px-6 py-3 text-base gap-2'
  };
  
  return (
    <button
      type={type}
      onClick={onClick}
      disabled={disabled || loading}
      className={`${baseClasses} ${variants[variant]} ${sizes[size]} ${disabled || loading ? 'opacity-50 cursor-not-allowed' : ''} ${className}`}
    >
      {loading ? (
        <div className="animate-spin rounded-full h-4 w-4 border-2 border-current border-t-transparent" />
      ) : icon ? (
        <span className="w-4 h-4">{icon}</span>
      ) : null}
      {children}
    </button>
  );
};
